from sage.misc.search import search
load( "auxi.py" )
load( "group_alg.py" )
load( "idempotents.py" )
load( "hnf.py" )
load( "diagram.py" )
load("diagram_from_lattice.py")
load("lattice.py")
load("lattice_from_diagram.py")
load("geral_info_new.py")
load("projeto_C2xC2.py")